### ISSUE TITLE
Changes in symbol processor does not invalidate compilation

### ISSUE THREAD

**Issue by yigit** [android/kotlin#45]
Seems like dependencies in the `ksp` classpath do not affect the task invalidation for the project compilation.

e.g. if you have
`:app`, `:processor` modules in a project where `processor` is a ksp configuration dependency

``` 
// app's gradle file

ksp(project(":processor"))
```

Changes in the `processor` project do not invalidate the compilation for app unless i invoke `clean`.

To reproduce, 

* compile the whole project
```
./gradlew :app:build --info
```
make changes in the processor
```
./gradlew :app:build --info
```

processor will be recompiled but  app is not recompiled.

**Comment by ting-yuan** [comment]
Some random update: Gradle does trigger the tasks correctly. It's the incremental compilation logic in `kotlinc` decides that there is no source change and doesn't trigger the processing and compilation. I'm trying to see how to inform `kotlinc` about the change.

**Comment by ting-yuan** [comment]
We disabled incremental compilation when ksp is used as a workaround in #77. @yigit would that be a concern to you?

**Comment by vRallev** [comment]
In my Kotlin compiler plugin I ran into the same issue. Since the compiler plugin comes with a Gradle plugin I fixed it there. I created a custom Gradle task that disables incremental compilation whenever the compiler plugin classpath contains a change, otherwise Kotlin compilation is incremental. That's better than always disabling incremental compilation. 

The corresponding ticket is here: https://youtrack.jetbrains.com/issue/KT-38570
